ips_kuka/joint_trajectory_controller:
  ros__parameters:
    joints:
    - ips_kuka_joint_1
    - ips_kuka_joint_2
    - ips_kuka_joint_3
    - ips_kuka_joint_4
    - ips_kuka_joint_5
    - ips_kuka_joint_6

    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_nonzero_velocity_at_trajectory_end: true
